inputs_dir: "/mnt/ris/aadel/mpnst/inputs"
demultiplex_dir: "/mnt/ris/aadel/mpnst/cappseq/demultiplexed"
rename_dir: "/mnt/ris/aadel/mpnst/cappseq/rename"
extracted_dir: "/mnt/ris/aadel/mpnst/cappseq/extracted"
hg38_fasta: "GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai"
hg38_fasta_ftp: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai"
hg38_bwa_index_ftp: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bwa_index.tar.gz"
hg38_bwa_index_zip: "GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bwa_index.tar.gz"
ref_dir: "/mnt/ris/aadel/mpnst/ref"
log_dir: "/mnt/ris/aadel/mnpst/logs"
