###   Parameters intended to be common across workflows   ###

blklist: "test/inputs/hg38-blacklist.v2.bed"
datadir: "test"
default_container: "/home/jeszyman/sing_containers/biotools.1.0.2.sif"
genome_fasta: "test/inputs/chr8.fa"
genome_ref: "test/ref/chr8.fa"
qcdir: "test/analysis/qc"
threads: 4

###   Unique properties from this repo   ###

cfdna_wgs_container: "/home/jeszyman/sing_containers/cfdna_wgs.1.0.0.sif"

cfdna_wgs_repo: "/home/jeszyman/repos/cfdna-wgs"

downsample:
  - "0.001"
  - "0.004"

frag_distro: "90_150"

gc5mb: "test/inputs/gc5mb.bed"

picard_jar: "/opt/picard/picard.jar"