#  Note: This script is tangled from code blocks in the Emacs Org-mode file at
#  https://github.com/jeszyman/cfdna-wgs/blob/master/cfdna-wgs.org. Changes
#  made directly to this file will be overwritten upon tangle from Org-mode.


threads: 4
data_dir: "test"
cfdna_wgs_script_dir: "workflow/scripts"
container: "${HOME}/sing_containers/biotools.1.0.2.sif"
cfdna_wgs_container: "${HOME}/sing_containers/biotools.1.0.2.sif"
picard_jar: "/opt/picard/picard.jar"

# Required reference files

adapter_fastq: "test/inputs/TruSeq3-PE.fa"
genome_fasta: "test/inputs/chr8.fa"
blacklist: "test/inputs/hg38-blacklist.v2.bed"

# Required parameters
MILREADS:
  - "1"

qscore: "20"