blacklist: "test/inputs/hg38-blacklist.v2.bed"

chrom_sizes: "test/inputs/hg38.chrom.sizes"

datadir: "test"

default_container: "/home/jeszyman/sing_containers/biotools.1.0.2.sif"

frag_distro: "90_150"

genome_fasta: "test/inputs/chr8.fa"

milreads: .002

cfdna_wgs_container: "/home/jeszyman/sing_containers/cfdna_wgs.1.0.0.sif"
cfdna_wgs_repo: "/home/jeszyman/repos/cfdna-wgs"



logdir: "test/logs"

picard_jar: "/opt/picard/picard.jar"

qcdir: "test/qc"

repo:
  cfdna_wgs: "/home/jeszyman/repos/cfdna-wgs"

cfdna_wgs_scriptdir: "/home/jeszyman/repos/cfdna-wgs/scripts"

threads: 4