# Integration testing is on software in the jeszyman/biotools dockerfile.
container: "~/sing_containers/biotools.sif"

# Required paths
#  (Data directory will contain all snakefile outputs in a sub-directory.)
data_dir: "test"
cfdna_wgs_script_dir: "workflow/scripts"

# Required reference files
adapter_fastq: "test/inputs/TruSeq3-PE.fa"
genome_fasta: "test/inputs/chr8.fa"
bwa_index: "test/inputs/chr8"
blacklist: "test/inputs/hg38-blacklist.v2.bed"

# Required parameters
threads: 4
MILREADS:
  - "10"
  - "20"