container: "/home/jeszyman/sing_containers/biotools.sif"        
raw_fq_dir: "test/fastq"
qc_dir: "test/qc"
log_dir: "test/logs"
threads: 4
inputs_dir: "test/inputs"
processed_fq_dir: "test/processed-fastq"
unpr_fq_dir: "test/unpaired-fastq"
bwa_index: "test/ref/chr8"
bam_dir: "test/bam"